name: create-a-blog-post # Name of the Github Actions

on:
  push:
    branches:
      - master #Event (Triggers the jobs to be done)

jobs:                                           #Jobs (Tasks)
  create-a-new-blog-on-Hashnode:
    runs-on: ubuntu-latest
    steps:
      #This will run the v4 of the checkout's action. Used when the workflow is using the repo's code
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Python Environment  # Install Python and its dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
          
      - name: Install Dependencies
        run: |
          pip install requests gql

      - name: Run Python Script
        run: python "Blog.py"   
        env:
          Hashnode-API_Key: ${{secrets.Hashnode_API_Key}} 
   
